# Generated by Django 5.0.9 on 2024-10-15 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="classes",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="hours",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
